name: Tests
on: [push]

jobs:
  rails:
    name: Rails Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler: 2.1.4
          bundler-cache: true

      - name: Clean appraisals
        run: bundle exec appraisal clean

      - name: Generate dependencies
        run: bundle exec appraisal install

      - name: Run the tests
        id: tests
        run: |
          bundle exec appraisal rake test
