name: Tests
on: [push]

jobs:
  rails:
    name: Rails Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7]
        gemfiles: ["gemfiles/rails_6.0.gemfile", "gemfiles/rails_6.1.gemfile"]
      fail-fast: false
    env:
      GEM_HOME: $HOME/.gem
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.2.14
          bundler-cache: true

      - name: Update system gem
        run: gem update --system

      - name: Clean appraisals
        run: bundle exec appraisal clean

      - name: Generate gemfiles
        run: bundle exec appraisal generate

      - name: Build Gemfile.lock
        run: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle install

      - name: Run the tests
        id: tests
        un: BUNDLE_GEMFILE=${{ matrix.gemfile }} bundle exec rake test
