name: Tests
on: [push]

jobs:
  rails:
    name: Rails Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rails 5.0
        env: GEM_HOME=$HOME/.gem
        run: gem install rails -v "~> 5.0.0"

      - name: Install Rails 5.1
        env: GEM_HOME=$HOME/.gem
        run: gem install rails -v "~> 5.1.0"

      - name: Install Rails 6.1
        env: GEM_HOME=$HOME/.gem
        run: gem install rails -v "~> 6.1.0"

      - name: Clean appraisals
        run: bundle exec appraisal clean

      - name: Generate appraisals
        run: bundle exec appraisal generate

      - name: Run the tests
        id: tests
        run: |
          bundle exec appraisal rake test
