name: Tests
on: [push]

jobs:
  rails:
    name: Rails Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [2.6, 2.7]
        appraisal-build: ["rails-6.0", "rails-6.1"]
      fail-fast: false
    env:
      GEM_HOME: $HOME/.gem
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler: 2.1.4
          bundler-cache: true

      - name: Use latest ruby gems
        if: ${{ matrix.ruby == '2.6' }
        run: gem update --system

      - name: Clean appraisals
        run: bundle exec appraisal clean

      - name: Generate dependencies
        run: bundle exec appraisal install
        continue-on-error: true

      - name: Run the tests
        if:
        id: tests
        run: bundle exec appraisal ${{ matrix.appraisal-build }} rake test
